# Generated by Django 3.0.6 on 2020-05-08 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_nse_top_gainers'),
    ]

    operations = [
        migrations.CreateModel(
            name='BSE_Top_Losers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=30)),
                ('high', models.FloatField(default=0)),
                ('low', models.FloatField(default=0)),
                ('last_price', models.FloatField(default=0)),
                ('prev_close', models.FloatField(default=0)),
                ('change', models.FloatField(default=0)),
                ('perc_loss', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='NSE_Top_Losers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=30)),
                ('high', models.FloatField(default=0)),
                ('low', models.FloatField(default=0)),
                ('last_price', models.FloatField(default=0)),
                ('prev_close', models.FloatField(default=0)),
                ('change', models.FloatField(default=0)),
                ('perc_loss', models.FloatField(default=0)),
            ],
        ),
    ]
