# Generated by Django 3.0.6 on 2020-05-08 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_bse_top_losers_nse_top_losers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Only_Buyers_BSE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=30)),
                ('sector', models.CharField(max_length=50)),
                ('bid_qty', models.IntegerField(default=0)),
                ('last_price', models.FloatField(default=0)),
                ('diff', models.FloatField(default=0)),
                ('perc_chng', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Only_Buyers_NSE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=30)),
                ('sector', models.CharField(max_length=50)),
                ('bid_qty', models.IntegerField(default=0)),
                ('last_price', models.FloatField(default=0)),
                ('diff', models.FloatField(default=0)),
                ('perc_chng', models.FloatField(default=0)),
            ],
        ),
    ]
