# Generated by Django 3.0.6 on 2020-05-09 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0004_only_buyers_bse_only_buyers_nse'),
    ]

    operations = [
        migrations.CreateModel(
            name='Only_Sellers_BSE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=30)),
                ('sector', models.CharField(max_length=50)),
                ('offer_qty', models.IntegerField(default=0)),
                ('last_price', models.FloatField(default=0)),
                ('diff', models.FloatField(default=0)),
                ('perc_chng', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Only_Sellers_NSE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=30)),
                ('sector', models.CharField(max_length=50)),
                ('offer_qty', models.IntegerField(default=0)),
                ('last_price', models.FloatField(default=0)),
                ('diff', models.FloatField(default=0)),
                ('perc_chng', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Price_Shockers_BSE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=30)),
                ('group', models.CharField(max_length=2)),
                ('sector', models.CharField(max_length=50)),
                ('current_price', models.FloatField(default=0)),
                ('previous_price', models.FloatField(default=0)),
                ('perc_chng', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Price_Shockers_NSE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=30)),
                ('group', models.CharField(max_length=2)),
                ('sector', models.CharField(max_length=50)),
                ('current_price', models.FloatField(default=0)),
                ('previous_price', models.FloatField(default=0)),
                ('perc_chng', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Volume_Shockers_BSE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=30)),
                ('group', models.CharField(max_length=2)),
                ('sector', models.CharField(max_length=50)),
                ('last_price', models.FloatField(default=0)),
                ('perc_chng1', models.FloatField(default=0)),
                ('avg_volume', models.FloatField(default=0)),
                ('perc_chng2', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Volume_Shockers_NSE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=30)),
                ('group', models.CharField(max_length=2)),
                ('sector', models.CharField(max_length=50)),
                ('last_price', models.FloatField(default=0)),
                ('perc_chng1', models.FloatField(default=0)),
                ('avg_volume', models.FloatField(default=0)),
                ('perc_chng2', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Week_High_BSE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=30)),
                ('group', models.CharField(max_length=2)),
                ('todays_high', models.FloatField(default=0)),
                ('todays_low', models.FloatField(default=0)),
                ('last_price', models.FloatField(default=0)),
                ('chng', models.FloatField(default=0)),
                ('perc_chng', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Week_High_NSE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=30)),
                ('todays_high', models.FloatField(default=0)),
                ('todays_low', models.FloatField(default=0)),
                ('last_price', models.FloatField(default=0)),
                ('chng', models.FloatField(default=0)),
                ('perc_chng', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Week_Low_BSE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=30)),
                ('group', models.CharField(max_length=2)),
                ('todays_high', models.FloatField(default=0)),
                ('todays_low', models.FloatField(default=0)),
                ('last_price', models.FloatField(default=0)),
                ('chng', models.FloatField(default=0)),
                ('perc_chng', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Week_Low_NSE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=30)),
                ('todays_high', models.FloatField(default=0)),
                ('todays_low', models.FloatField(default=0)),
                ('last_price', models.FloatField(default=0)),
                ('chng', models.FloatField(default=0)),
                ('perc_chng', models.FloatField(default=0)),
            ],
        ),
    ]
