# Generated by Django 3.0.6 on 2020-05-09 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0005_only_sellers_bse_only_sellers_nse_price_shockers_bse_price_shockers_nse_volume_shockers_bse_volume_s'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volume_shockers_bse',
            name='avg_volume',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='volume_shockers_bse',
            name='perc_chng2',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='volume_shockers_nse',
            name='avg_volume',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='volume_shockers_nse',
            name='perc_chng2',
            field=models.IntegerField(default=0),
        ),
    ]
