# Generated by Django 3.0.6 on 2020-05-18 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0006_auto_20200509_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bse_top_gainers',
            name='high',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
        ),
    ]
